# fly.toml app configuration file generated for backend-small-moon-8593 on 2025-05-28T07:23:54+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-small-moon-8593'
primary_region = 'jnb'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_DEBUG = 'true'
  APP_ENV = 'production'
  APP_KEY = 'base64:13TiD5ZEzuL+38J/MG11nGY3AYLsefsEzhwHD1q/6bI='
  DB_CONNECTION = 'sqlite'
  DB_DATABASE = '/var/www/html/storage/database/database.sqlite'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SANCTUM_STATEFUL_DOMAINS = 'localhost,localhost:5173,127.0.0.1,::1,https://frontend-wandering-dust-3957.fly.dev'
  SESSION_DOMAIN = 'localhost'
  SESSION_DRIVER = 'cookie'
  SESSION_ENCRYPT = 'false'
  SESSION_LIFETIME = '120'
  SESSION_PATH = '/'
  SESSION_SECURE_COOKIE = 'true'

[[mounts]]
  source = 'storage_vol'
  destination = '/var/www/html/storage'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "./deploy.sh"